services:
  ctf-app:
    build: .
    container_name: operation-digital-turf-war
    ports:
      - "5000:5000"
    volumes:
      - ./app/logs:/ctf/logs
    env_file:
      - .env
    restart: unless-stopped
